# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11ff9490d40246ec76c541eecf67effbbcc5e3f4fa5f4c97912e5b40aa1a8f67fcb5c1d684cc81abb4e27da55a3979382098ff70d8e507a9bb9e02a83f1124e8

test:
  secret_key_base: 61b1220f0b09c7bca2482164d2f0c52f1d54389f6a0404aef61e1f9d9d56f25754b31e06a98ab1df757b5a35cb0fe2a10fb28b9dad67a0af4fe07a27cfc12c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
